jiminy: jiminy::FileDevice Class Reference
jiminy::FileDevice Class Reference
Class to manipulate a file.
#include <FileDevice.h>
Public Member Functions
FileDevice (std::string const &filename)
int64_t size (void) override
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
hresult_t resize (int64_t sizeIn) override
resize the device to provided size.
hresult_t seek (int64_t pos) override
Move the current position cursor to pos if possible.
int64_t pos (void) override
int64_t bytesAvailable (void) override
Returns the number of bytes that are available for reading. Commonly used with sequential device.
int64_t readData (void *data, int64_t dataSize) override
Read data in the device.
int64_t writeData (void const *data, int64_t dataSize) override
Write data in the device.
std::string const & name (void) const
Public Member Functions inherited from jiminy::AbstractIODevice
hresult_t open (enum OpenMode mode)
Open the device.
hresult_t close (void)
Write data in the device.
enum OpenMode openModes (void) const
enum OpenMode supportedModes (void) const
bool_t isWritable (void) const
bool_t isReadable (void) const
bool_t isOpen (void) const
virtual bool_t isSequential (void) const
template<typename T >
hresult_t write (T const &valueIn)
Write data in the device.
virtual hresult_t write (void const *data, int64_t dataSize)
Write data in the device.
template<typename T >
hresult_t read (T &valueIn)
Read data in the device.
virtual hresult_t read (void *data, int64_t dataSize)
Read data from the device.
hresult_t getLastError (void) const
Retrieve the latest error. Usefull for call that do not return an error code directly.
virtual hresult_t setBlockingMode (bool_t shouldBlock)
Set the device blocking fashion.
bool_t isBackendValid ()
Set the device backend (reset the old one if any).
virtual void setBackend (std::unique_ptr< AbstractIODevice > io)
Set the device backend (reset the old one if any).
virtual void removeBackend (void)
Reset the device backend.
template<>
hresult_t read (std::vector< uint8_t > &v)
template<>
hresult_t read (std::vector< char_t > &v)
template<>
hresult_t write (std::string const &str)
template<>
hresult_t write (std::vector< uint8_t > const &v)
template<>
hresult_t write (std::vector< char_t > const &v)
template<>
hresult_t write (std::vector< uint64_t > const &v)
Protected Member Functions
hresult_t doOpen (enum OpenMode mode) override
hresult_t doClose (void) override
Protected Attributes
std::string filename_
int32_t fileDescriptor_
File descriptor.
Protected Attributes inherited from jiminy::AbstractIODevice
hresult_t lastError_ {hresult_t::SUCCESS}
Latest generated error.
std::unique_ptr< AbstractIODevice > io_ {nullptr}
Backend to use if any.
Detailed Description
Class to manipulate a file.
Definition at line 20 of file FileDevice.h.
Member Function Documentation
bytesAvailable()
int64_t jiminy::FileDevice::bytesAvailable (void) override virtual
Returns the number of bytes that are available for reading. Commonly used with sequential device.
Returns
The available bytesfor reading.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 178 of file FileDevice.cc.
References jiminy::AbstractIODevice::isReadable(), jiminy::AbstractIODevice::pos(), and jiminy::AbstractIODevice::size().
pos()
int64_t jiminy::FileDevice::pos (void) override virtual
Returns
The current cursor position (0 if there is not concept of position cursor).
Reimplemented from jiminy::AbstractIODevice.
Definition at line 155 of file FileDevice.cc.
References jiminy::AbstractIODevice::lastError_.
readData()
int64_t jiminy::FileDevice::readData (void * data, int64_t dataSize) override virtual
Read data in the device.
Parameters
data Buffer of data to read.
dataSize Number of bytes to read.
Returns
the number of bytes read, -1 in case of error
Implements jiminy::AbstractIODevice.
Definition at line 187 of file FileDevice.cc.
References jiminy::AbstractIODevice::lastError_, and jiminy::AbstractIODevice::read().
seek()
hresult_t jiminy::FileDevice::seek (int64_t pos) override virtual
Move the current position cursor to pos if possible.
Parameters
pos Desired new position of the cursor.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 143 of file FileDevice.cc.
References jiminy::AbstractIODevice::lastError_.
size()
int64_t jiminy::FileDevice::size (void) override virtual
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
Returns
The size of the device.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 166 of file FileDevice.cc.
References jiminy::AbstractIODevice::lastError_.
writeData()
int64_t jiminy::FileDevice::writeData (void const * data, int64_t dataSize) override virtual
Write data in the device.
Parameters
data Buffer of data to write.
dataSize Number of bytes to write.
Returns
the number of bytes written, -1 in case of error
Implements jiminy::AbstractIODevice.
Definition at line 198 of file FileDevice.cc.
References jiminy::AbstractIODevice::lastError_, and jiminy::AbstractIODevice::write().
The documentation for this class was generated from the following files:
core/include/jiminy/core/io/FileDevice.h
core/src/io/FileDevice.cc