jiminy: jiminy::AbstractSensorTpl< T > Class Template Reference
jiminy::AbstractSensorTpl< T > Class Template Reference
Public Member Functions
AbstractSensorTpl (AbstractSensorTpl const &abstractSensor)=delete
AbstractSensorTpl & operator= (AbstractSensorTpl const &other)=delete
AbstractSensorTpl (std::string const &name)
auto shared_from_this ()
auto shared_from_this () const
virtual void resetAll (void) override
Reset the internal state of the sensors.
void updateTelemetryAll (void) override final
Update the internal buffers of the telemetry associated with variables monitored every sensors of the same type than the current one.
virtual hresult_t setOptions (configHolder_t const &sensorOptions) override
Set the configuration options of the sensor.
virtual hresult_t setOptionsAll (configHolder_t const &sensorOptions) override final
Set the same configuration options of any sensor of the same type than the current one.
virtual int32_t const & getIdx (void) const override final
Get sensorIdx_.
virtual std::string const & getType (void) const override final
Get type_.
virtual std::vector< std::string > const & getFieldnames (void) const final
Get the name of each element of the data measured by the sensor.
virtual uint32_t getSize (void) const override final
It is the size of the sensor's data vector.
virtual Eigen::Ref< vectorN_t const > get (void) const override final
Get the measurement of the sensor at the current time.
virtual hresult_t setAll (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, Eigen::Ref< vectorN_t const > const &a, vectorN_t const &uMotor) override final
Request every sensors of the same type than the current one to record data based of the input data.
template<>
std::string const type_ ("ImuSensor")
template<>
bool_t const areFieldnamesGrouped_ (false)
template<>
std::vector< std::string > const fieldNames_ ({"Quatx", "Quaty", "Quatz", "Quatw", "Gyrox", "Gyroy", "Gyroz", "Accelx", "Accely", "Accelz"})
template<>
std::string const type_ ("ForceSensor")
template<>
bool_t const areFieldnamesGrouped_ (false)
template<>
std::vector< std::string > const fieldNames_ ({"FX", "FY", "FZ"})
template<>
std::string const type_ ("EncoderSensor")
template<>
bool_t const areFieldnamesGrouped_ (true)
template<>
std::vector< std::string > const fieldNames_ ({"Q", "V"})
template<>
std::string const type_ ("EffortSensor")
template<>
bool_t const areFieldnamesGrouped_ (true)
template<>
std::vector< std::string > const fieldNames_ ({"U"})
Public Member Functions inherited from jiminy::AbstractSensorBase
virtual configHolder_t getDefaultSensorOptions (void)
Dictionary gathering the configuration options shared between sensors.
AbstractSensorBase (AbstractSensorBase const &abstractSensor)=delete
Forbid the copy of the class.
AbstractSensorBase & operator= (AbstractSensorBase const &other)=delete
AbstractSensorBase (std::string const &name)
Constructor.
template<typename T >
std::shared_ptr< T > shared_from (T *derived)
virtual hresult_t refreshProxies (void)=0
Refresh the proxies.
virtual hresult_t configureTelemetry (std::shared_ptr< TelemetryData > telemetryData, std::string const &objectPrefixName="")
Configure the telemetry of the sensor.
void updateTelemetry (void)
Update the internal buffers of the telemetry associated with variables monitored by the sensor.
configHolder_t getOptions (void) const
Get the configuration options of the sensor.
bool_t const & getIsInitialized (void) const
Get isInitialized_.
bool_t const & getIsAttached (void) const
Get isAttached_.
bool_t const & getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
std::string const & getName (void) const
Get name_.
Static Public Attributes
static std::string const type_
static std::vector< std::string > const fieldNames_
static bool_t const areFieldnamesGrouped_
Protected Member Functions
virtual Eigen::Ref< vectorN_t > get (void) override final
virtual Eigen::Ref< vectorN_t > data (void) override final
Get a Eigen Reference to a Eigen Vector corresponding to the last data recorded (or being recorded) by the sensor.
Protected Member Functions inherited from jiminy::AbstractSensorBase
virtual hresult_t set (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, Eigen::Ref< vectorN_t const > const &a, vectorN_t const &uMotor)=0
Request the sensor to record data based of the input data.
virtual void skewMeasurement (void)
Add white noise and bias to the measurement buffer.
Protected Attributes
int32_t sensorIdx_
Protected Attributes inherited from jiminy::AbstractSensorBase
configHolder_t sensorOptionsHolder_
Dictionary with the parameters of the sensor.
bool_t isInitialized_
Flag to determine whether the sensor has been initialized or not.
bool_t isAttached_
Flag to determine whether the sensor is attached to a robot.
bool_t isTelemetryConfigured_
Flag to determine whether the telemetry of the sensor has been initialized or not.
Robot const * robot_
Robot for which the command and internal dynamics.
std::string name_
Name of the sensor.
Private Member Functions
virtual hresult_t attach (Robot const *robot, SensorSharedDataHolder_t *sharedHolder) override final
Attach the sensor to a robot.
virtual hresult_t detach (void) override final
Detach the sensor from the robot.
virtual std::string getTelemetryName (void) const override final
Get the name of the sensor in the telemetry.
virtual hresult_t interpolateData (void) override final
Set the measurement buffer with the real data interpolated at the current time.
virtual hresult_t generateMeasurementAll (void) override final
Set the measurement buffer with the real data, but skewed with white noise and bias.
void clearDataBuffer (void)
Private Attributes
SensorSharedDataHolder_t * sharedHolder_
Additional Inherited Members
Public Attributes inherited from jiminy::AbstractSensorBase
std::unique_ptr< abstractSensorOptions_t const > baseSensorOptions_
Structure with the parameters of the sensor.
Detailed Description
template<class T>
class jiminy::AbstractSensorTpl< T >
Definition at line 435 of file AbstractSensor.h.
Member Function Documentation
attach()
template<typename T > hresult_t jiminy::AbstractSensorTpl< T >::attach (Robot const * robot, SensorSharedDataHolder_t * sharedHolder) final override private virtual
Attach the sensor to a robot.
This method must be called before initializing the sensor.
Implements jiminy::AbstractSensorBase.
Definition at line 27 of file AbstractSensor.tpp.
data()
template<typename T > Eigen::Ref< vectorN_t > jiminy::AbstractSensorTpl< T >::data (void) inline final override protected virtual
Get a Eigen Reference to a Eigen Vector corresponding to the last data recorded (or being recorded) by the sensor.
More precisely, it corresponds to the memory associated with the most recent data in the buffer of previously recorded (non-delayed) data. It does not have to be filled up at this stage.
Returns
Eigen Reference to a Eigen Vector corresponding to the last data recorded
Implements jiminy::AbstractSensorBase.
Definition at line 232 of file AbstractSensor.tpp.
Referenced by jiminy::AbstractSensorTpl< ImuSensor >::resetAll().
get()
template<typename T > Eigen::Ref< vectorN_t const > jiminy::AbstractSensorTpl< T >::get (void) const inline final override virtual
Get the measurement of the sensor at the current time.
Note that the current time corresponds to the last time sensor data was recorded. If the delay of the sensor is nonzero, then an interpolation method is used to compute the delayed measurement based on a buffer of previously recorded non-delayed data.
Returns
Eigen reference to a Eigen Vector where to store of sensor measurement. It can be an actual vectorN_t, or the extraction of a column vector from a higher dimensional tensor.
Implements jiminy::AbstractSensorBase.
Definition at line 220 of file AbstractSensor.tpp.
Referenced by jiminy::AbstractSensorTpl< ImuSensor >::get().
getIdx()
template<typename T > int32_t const & jiminy::AbstractSensorTpl< T >::getIdx (void) const final override virtual
Get sensorIdx_.
It is the index of the sensor of the global shared buffer.
Implements jiminy::AbstractSensorBase.
Definition at line 184 of file AbstractSensor.tpp.
getTelemetryName()
template<typename T > std::string jiminy::AbstractSensorTpl< T >::getTelemetryName (void) const final override private virtual
Get the name of the sensor in the telemetry.
Note that the telemetry management is independent for each sensor instead of gatering them by type. Nevertheles, the element recorded by a given sensor are prefixed with the type and name of the sensor, so that it appears as if they were actually gathered.
Implements jiminy::AbstractSensorBase.
Definition at line 207 of file AbstractSensor.tpp.
getType()
template<typename T > std::string const & jiminy::AbstractSensorTpl< T >::getType (void) const final override virtual
Get type_.
It is the type of the sensor.
Implements jiminy::AbstractSensorBase.
Definition at line 190 of file AbstractSensor.tpp.
Referenced by jiminy::AbstractSensorTpl< ImuSensor >::getTelemetryName().
resetAll()
template<typename T > void jiminy::AbstractSensorTpl< T >::resetAll (void) override virtual
Reset the internal state of the sensors.
This method resets the internal state of the sensor and unset the configuration of the telemetry.
Remarks
This method is not intended to be called manually. The Robot to which the sensor is added is taking care of it when its own reset method is called.
Implements jiminy::AbstractSensorBase.
Definition at line 128 of file AbstractSensor.tpp.
setAll()
template<typename T > hresult_t jiminy::AbstractSensorTpl< T >::setAll (float64_t const & t, Eigen::Ref< vectorN_t const > const & q, Eigen::Ref< vectorN_t const > const & v, Eigen::Ref< vectorN_t const > const & a, vectorN_t const & uMotor) final override virtual
Request every sensors of the same type than the current one to record data based of the input data.
It assumes that the internal state of the robot is consistent with the input arguments.
Remarks
This method is not intended to be called manually. The Robot to which the sensor is added is taking care of it while updating the state of the sensors.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[in] a Current acceleration vector
[in] u Current motor effort vector
Returns
Return code to determine whether the execution of the method was successful.
Implements jiminy::AbstractSensorBase.
Definition at line 367 of file AbstractSensor.tpp.
setOptions()
template<typename T > hresult_t jiminy::AbstractSensorTpl< T >::setOptions (configHolder_t const & sensorOptions) override virtual
Set the configuration options of the sensor.
Parameters
[in] sensorOptions Dictionary with the parameters of the sensor
Reimplemented from jiminy::AbstractSensorBase.
Reimplemented in jiminy::ImuSensor.
Definition at line 153 of file AbstractSensor.tpp.
setOptionsAll()
template<typename T > hresult_t jiminy::AbstractSensorTpl< T >::setOptionsAll (configHolder_t const & sensorOptions) final override virtual
Set the same configuration options of any sensor of the same type than the current one.
Parameters
[in] sensorOptions Dictionary with the parameters used for any sensor
Implements jiminy::AbstractSensorBase.
Definition at line 168 of file AbstractSensor.tpp.
updateTelemetryAll()
template<typename T > void jiminy::AbstractSensorTpl< T >::updateTelemetryAll (void) final override virtual
Update the internal buffers of the telemetry associated with variables monitored every sensors of the same type than the current one.
Remarks
This method is not intended to be called manually. The Robot to which the sensor is added is taking care of it before flushing the telemetry data at
Implements jiminy::AbstractSensorBase.
Definition at line 447 of file AbstractSensor.tpp.
The documentation for this class was generated from the following files:
core/include/jiminy/core/robot/AbstractSensor.h
core/include/jiminy/core/robot/AbstractSensor.tpp