jiminy: jiminy::AbstractSensorBase Class Reference
jiminy::AbstractSensorBase Class Reference abstract
Classes
struct abstractSensorOptions_t
Public Member Functions
virtual configHolder_t getDefaultSensorOptions (void)
Dictionary gathering the configuration options shared between sensors.
AbstractSensorBase (AbstractSensorBase const &abstractSensor)=delete
Forbid the copy of the class.
AbstractSensorBase & operator= (AbstractSensorBase const &other)=delete
AbstractSensorBase (std::string const &name)
Constructor.
template<typename T >
std::shared_ptr< T > shared_from (T *derived)
virtual void resetAll (void)=0
Reset the internal state of the sensors.
virtual hresult_t refreshProxies (void)=0
Refresh the proxies.
virtual hresult_t configureTelemetry (std::shared_ptr< TelemetryData > telemetryData, std::string const &objectPrefixName="")
Configure the telemetry of the sensor.
void updateTelemetry (void)
Update the internal buffers of the telemetry associated with variables monitored by the sensor.
virtual void updateTelemetryAll (void)=0
Update the internal buffers of the telemetry associated with variables monitored every sensors of the same type than the current one.
virtual hresult_t setOptions (configHolder_t const &sensorOptions)
Set the configuration options of the sensor.
virtual hresult_t setOptionsAll (configHolder_t const &sensorOptions)=0
Set the same configuration options of any sensor of the same type than the current one.
configHolder_t getOptions (void) const
Get the configuration options of the sensor.
virtual hresult_t setAll (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, Eigen::Ref< vectorN_t const > const &a, vectorN_t const &uMotor)=0
Request every sensors of the same type than the current one to record data based of the input data.
virtual Eigen::Ref< vectorN_t const > get (void) const =0
Get the measurement of the sensor at the current time.
bool_t const & getIsInitialized (void) const
Get isInitialized_.
bool_t const & getIsAttached (void) const
Get isAttached_.
bool_t const & getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
std::string const & getName (void) const
Get name_.
virtual int32_t const & getIdx (void) const =0
Get sensorIdx_.
virtual std::string const & getType (void) const =0
Get type_.
virtual uint32_t getSize (void) const =0
It is the size of the sensor's data vector.
virtual std::vector< std::string > const & getFieldnames (void) const =0
Get the name of each element of the data measured by the sensor.
Public Attributes
std::unique_ptr< abstractSensorOptions_t const > baseSensorOptions_
Structure with the parameters of the sensor.
Protected Member Functions
virtual hresult_t set (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, Eigen::Ref< vectorN_t const > const &a, vectorN_t const &uMotor)=0
Request the sensor to record data based of the input data.
virtual hresult_t attach (Robot const *robot, SensorSharedDataHolder_t *sharedHolder)=0
Attach the sensor to a robot.
virtual hresult_t detach (void)=0
Detach the sensor from the robot.
virtual Eigen::Ref< vectorN_t > data (void)=0
Get a Eigen Reference to a Eigen Vector corresponding to the last data recorded (or being recorded) by the sensor.
virtual Eigen::Ref< vectorN_t > get (void)=0
virtual std::string getTelemetryName (void) const =0
Get the name of the sensor in the telemetry.
virtual hresult_t interpolateData (void)=0
Set the measurement buffer with the real data interpolated at the current time.
virtual void skewMeasurement (void)
Add white noise and bias to the measurement buffer.
virtual hresult_t generateMeasurementAll (void)=0
Set the measurement buffer with the real data, but skewed with white noise and bias.
Protected Attributes
configHolder_t sensorOptionsHolder_
Dictionary with the parameters of the sensor.
bool_t isInitialized_
Flag to determine whether the sensor has been initialized or not.
bool_t isAttached_
Flag to determine whether the sensor is attached to a robot.
bool_t isTelemetryConfigured_
Flag to determine whether the telemetry of the sensor has been initialized or not.
Robot const * robot_
Robot for which the command and internal dynamics.
std::string name_
Name of the sensor.
Private Attributes
friend Robot
TelemetrySender telemetrySender_
Telemetry sender of the sensor used to register and update telemetry variables.
Friends
template<typename T >
class AbstractSensorTpl
Detailed Description
Definition at line 64 of file AbstractSensor.h.
Constructor & Destructor Documentation
AbstractSensorBase()
jiminy::AbstractSensorBase::AbstractSensorBase (std::string const & name)
Constructor.
Parameters
[in] name Name of the sensor
Definition at line 8 of file AbstractSensor.cc.
References getDefaultSensorOptions(), and setOptions().
Member Function Documentation
attach()
virtual hresult_t jiminy::AbstractSensorBase::attach (Robot const * robot, SensorSharedDataHolder_t * sharedHolder) protected pure virtual
Attach the sensor to a robot.
This method must be called before initializing the sensor.
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
configureTelemetry()
hresult_t jiminy::AbstractSensorBase::configureTelemetry (std::shared_ptr< TelemetryData > telemetryData, std::string const & objectPrefixName = "") virtual
Configure the telemetry of the sensor.
This method connects the controller-specific telemetry sender to a given telemetry data (which is unique for a given exoskeleton robot), so that it is later possible to register the variables that one want to monitor. Finally, the telemetry recoder logs every registered variables at each timestep in a memory buffer.
Remarks
This method is not intended to be called manually. The Robot to which the sensor is added is taking care of it before flushing the telemetry data at the end of each simulation steps.
Parameters
[in] telemetryData Shared pointer to the robot-wide telemetry data object
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 22 of file AbstractSensor.cc.
data()
virtual Eigen::Ref<vectorN_t> jiminy::AbstractSensorBase::data (void) protected pure virtual
Get a Eigen Reference to a Eigen Vector corresponding to the last data recorded (or being recorded) by the sensor.
More precisely, it corresponds to the memory associated with the most recent data in the buffer of previously recorded (non-delayed) data. It does not have to be filled up at this stage.
Returns
Eigen Reference to a Eigen Vector corresponding to the last data recorded
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
get()
virtual Eigen::Ref<vectorN_t const> jiminy::AbstractSensorBase::get (void) const pure virtual
Get the measurement of the sensor at the current time.
Note that the current time corresponds to the last time sensor data was recorded. If the delay of the sensor is nonzero, then an interpolation method is used to compute the delayed measurement based on a buffer of previously recorded non-delayed data.
Returns
Eigen reference to a Eigen Vector where to store of sensor measurement. It can be an actual vectorN_t, or the extraction of a column vector from a higher dimensional tensor.
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
getIdx()
virtual int32_t const& jiminy::AbstractSensorBase::getIdx (void) const pure virtual
Get sensorIdx_.
It is the index of the sensor of the global shared buffer.
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
getIsAttached()
bool_t const& jiminy::AbstractSensorBase::getIsAttached (void) const
Get isAttached_.
It is a flag used to determine if the sensor has been attached to a robot.
getIsInitialized()
bool_t const & jiminy::AbstractSensorBase::getIsInitialized (void) const
Get isInitialized_.
It is a flag used to determine if the sensor has been initialized.
Remarks
Note that a sensor can be considered initialized even if its telemetry is not properly configured. If not, it is the only thing to do before being ready to use.
Definition at line 97 of file AbstractSensor.cc.
References isInitialized_.
getIsTelemetryConfigured()
bool_t const & jiminy::AbstractSensorBase::getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
It is a flag used to determine if the telemetry of the controller has been initialized.
Definition at line 102 of file AbstractSensor.cc.
References isTelemetryConfigured_.
getName()
std::string const & jiminy::AbstractSensorBase::getName (void) const
Get name_.
It is the name of the sensor.
Definition at line 107 of file AbstractSensor.cc.
References name_.
getOptions()
configHolder_t jiminy::AbstractSensorBase::getOptions (void) const
Get the configuration options of the sensor.
Returns
Dictionary with the parameters of the sensor
Definition at line 92 of file AbstractSensor.cc.
References sensorOptionsHolder_.
getTelemetryName()
virtual std::string jiminy::AbstractSensorBase::getTelemetryName (void) const protected pure virtual
Get the name of the sensor in the telemetry.
Note that the telemetry management is independent for each sensor instead of gatering them by type. Nevertheles, the element recorded by a given sensor are prefixed with the type and name of the sensor, so that it appears as if they were actually gathered.
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
getType()
virtual std::string const& jiminy::AbstractSensorBase::getType (void) const pure virtual
Get type_.
It is the type of the sensor.
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
refreshProxies()
virtual hresult_t jiminy::AbstractSensorBase::refreshProxies (void) pure virtual
Refresh the proxies.
Remarks
This method is not intended to be called manually. The Robot to which the motor is added is taking care of it when its own refresh method is called.
Implemented in jiminy::EffortSensor, jiminy::EncoderSensor, jiminy::ForceSensor, and jiminy::ImuSensor.
Referenced by jiminy::AbstractSensorTpl< ImuSensor >::resetAll().
resetAll()
virtual void jiminy::AbstractSensorBase::resetAll (void) pure virtual
Reset the internal state of the sensors.
This method resets the internal state of the sensor and unset the configuration of the telemetry.
Remarks
This method is not intended to be called manually. The Robot to which the sensor is added is taking care of it when its own reset method is called.
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
set()
virtual hresult_t jiminy::AbstractSensorBase::set (float64_t const & t, Eigen::Ref< vectorN_t const > const & q, Eigen::Ref< vectorN_t const > const & v, Eigen::Ref< vectorN_t const > const & a, vectorN_t const & uMotor) protected pure virtual
Request the sensor to record data based of the input data.
It assumes that the internal state of the robot is consistent with the input arguments.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[in] a Current acceleration vector
[in] uMotor Current motor effort vector
Returns
Return code to determine whether the execution of the method was successful.
Implemented in jiminy::EffortSensor, jiminy::EncoderSensor, jiminy::ForceSensor, and jiminy::ImuSensor.
setAll()
virtual hresult_t jiminy::AbstractSensorBase::setAll (float64_t const & t, Eigen::Ref< vectorN_t const > const & q, Eigen::Ref< vectorN_t const > const & v, Eigen::Ref< vectorN_t const > const & a, vectorN_t const & uMotor) pure virtual
Request every sensors of the same type than the current one to record data based of the input data.
It assumes that the internal state of the robot is consistent with the input arguments.
Remarks
This method is not intended to be called manually. The Robot to which the sensor is added is taking care of it while updating the state of the sensors.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[in] a Current acceleration vector
[in] u Current motor effort vector
Returns
Return code to determine whether the execution of the method was successful.
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
setOptions()
hresult_t jiminy::AbstractSensorBase::setOptions (configHolder_t const & sensorOptions) virtual
Set the configuration options of the sensor.
Parameters
[in] sensorOptions Dictionary with the parameters of the sensor
Reimplemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, jiminy::AbstractSensorTpl< ImuSensor >, and jiminy::ImuSensor.
Definition at line 85 of file AbstractSensor.cc.
References baseSensorOptions_, and sensorOptionsHolder_.
Referenced by AbstractSensorBase().
setOptionsAll()
virtual hresult_t jiminy::AbstractSensorBase::setOptionsAll (configHolder_t const & sensorOptions) pure virtual
Set the same configuration options of any sensor of the same type than the current one.
Parameters
[in] sensorOptions Dictionary with the parameters used for any sensor
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
updateTelemetryAll()
virtual void jiminy::AbstractSensorBase::updateTelemetryAll (void) pure virtual
Update the internal buffers of the telemetry associated with variables monitored every sensors of the same type than the current one.
Remarks
This method is not intended to be called manually. The Robot to which the sensor is added is taking care of it before flushing the telemetry data at
Implemented in jiminy::AbstractSensorTpl< T >, jiminy::AbstractSensorTpl< EffortSensor >, jiminy::AbstractSensorTpl< ForceSensor >, jiminy::AbstractSensorTpl< EncoderSensor >, and jiminy::AbstractSensorTpl< ImuSensor >.
The documentation for this class was generated from the following files:
core/include/jiminy/core/robot/AbstractSensor.h
core/src/robot/AbstractSensor.cc