jiminy: jiminy::AbstractIODevice Class Reference
jiminy::AbstractIODevice Class Reference abstract
Base interface class for all I/O devices.
#include <AbstractIODevice.h>
Public Member Functions
hresult_t open (enum OpenMode mode)
Open the device.
hresult_t close (void)
Write data in the device.
enum OpenMode openModes (void) const
enum OpenMode supportedModes (void) const
bool_t isWritable (void) const
bool_t isReadable (void) const
bool_t isOpen (void) const
virtual bool_t isSequential (void) const
virtual int64_t size (void)
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
virtual hresult_t seek (int64_t pos)
Move the current position cursor to pos if possible.
virtual int64_t pos (void)
virtual hresult_t resize (int64_t size)
resize the device to provided size.
virtual int64_t bytesAvailable (void)
Returns the number of bytes that are available for reading. Commonly used with sequential device.
template<typename T >
hresult_t write (T const &valueIn)
Write data in the device.
virtual hresult_t write (void const *data, int64_t dataSize)
Write data in the device.
virtual int64_t writeData (void const *data, int64_t dataSize)=0
Write data in the device.
template<typename T >
hresult_t read (T &valueIn)
Read data in the device.
virtual hresult_t read (void *data, int64_t dataSize)
Read data from the device.
virtual int64_t readData (void *data, int64_t dataSize)=0
Read data in the device.
hresult_t getLastError (void) const
Retrieve the latest error. Usefull for call that do not return an error code directly.
virtual hresult_t setBlockingMode (bool_t shouldBlock)
Set the device blocking fashion.
bool_t isBackendValid ()
Set the device backend (reset the old one if any).
virtual void setBackend (std::unique_ptr< AbstractIODevice > io)
Set the device backend (reset the old one if any).
virtual void removeBackend (void)
Reset the device backend.
template<>
hresult_t read (std::vector< uint8_t > &v)
template<>
hresult_t read (std::vector< char_t > &v)
template<>
hresult_t write (std::string const &str)
template<>
hresult_t write (std::vector< uint8_t > const &v)
template<>
hresult_t write (std::vector< char_t > const &v)
template<>
hresult_t write (std::vector< uint64_t > const &v)
Protected Member Functions
virtual hresult_t doOpen (enum OpenMode mode)=0
virtual hresult_t doClose (void)=0
Protected Attributes
hresult_t lastError_ {hresult_t::SUCCESS}
Latest generated error.
std::unique_ptr< AbstractIODevice > io_ {nullptr}
Backend to use if any.
Detailed Description
Base interface class for all I/O devices.
Definition at line 44 of file AbstractIODevice.h.
Member Function Documentation
bytesAvailable()
int64_t jiminy::AbstractIODevice::bytesAvailable (void) virtual
Returns the number of bytes that are available for reading. Commonly used with sequential device.
Returns
The available bytesfor reading.
Reimplemented in jiminy::MemoryDevice, and jiminy::FileDevice.
Definition at line 145 of file AbstractIODevice.cc.
Referenced by size().
close()
hresult_t jiminy::AbstractIODevice::close (void)
Write data in the device.
The default implementation manage only POD type. For specific type, the template shall be extended with specific implementation.
Parameters
Value to write into the device.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Definition at line 69 of file AbstractIODevice.cc.
Referenced by jiminy::TelemetryRecorder::writeDataBinary().
getLastError()
hresult_t jiminy::AbstractIODevice::getLastError (void) const
Retrieve the latest error. Usefull for call that do not return an error code directly.
Returns
The latest generated error.
Definition at line 150 of file AbstractIODevice.cc.
References lastError_.
isOpen()
bool_t jiminy::AbstractIODevice::isOpen (void) const
Returns
true if the device is opened, false otherwise.
Definition at line 111 of file AbstractIODevice.cc.
References jiminy::NOT_OPEN.
Referenced by jiminy::TelemetryRecorder::writeDataBinary().
isReadable()
bool_t jiminy::AbstractIODevice::isReadable (void) const
Returns
true if the device is readable, false otherwise.
Definition at line 106 of file AbstractIODevice.cc.
References jiminy::READ_ONLY, and jiminy::READ_WRITE.
Referenced by jiminy::FileDevice::bytesAvailable().
isSequential()
bool_t jiminy::AbstractIODevice::isSequential (void) const virtual
Returns
true if the device is sequential (i.e socket), false if the device support random-access (i.e regular file).
Reimplemented in jiminy::MemoryDevice.
Definition at line 116 of file AbstractIODevice.cc.
isWritable()
bool_t jiminy::AbstractIODevice::isWritable (void) const
Returns
true if the device is writable, false otherwise.
Definition at line 101 of file AbstractIODevice.cc.
References jiminy::READ_WRITE, and jiminy::WRITE_ONLY.
open()
hresult_t jiminy::AbstractIODevice::open (enum OpenMode mode)
Open the device.
Parameters
mode Mode to apply for opening the device.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Definition at line 44 of file AbstractIODevice.cc.
Referenced by jiminy::TelemetryRecorder::writeDataBinary().
openModes()
enum OpenMode jiminy::AbstractIODevice::openModes (void) const
Returns
The current opening modes.
Definition at line 91 of file AbstractIODevice.cc.
pos()
int64_t jiminy::AbstractIODevice::pos (void) virtual
Returns
The current cursor position (0 if there is not concept of position cursor).
Reimplemented in jiminy::MemoryDevice, and jiminy::FileDevice.
Definition at line 140 of file AbstractIODevice.cc.
Referenced by jiminy::FileDevice::bytesAvailable().
read() [1/2]
template<typename T > hresult_t jiminy::AbstractIODevice::read (T & valueIn)
Read data in the device.
The default implementation manage only POD type. For specific type, the template shall be extended with specific implementation.
Parameters
Value to store read data.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Definition at line 24 of file AbstractIODevice.tpp.
Referenced by jiminy::FileDevice::readData(), and removeBackend().
read() [2/2]
hresult_t jiminy::AbstractIODevice::read (void * data, int64_t dataSize) virtual
Read data from the device.
Parameters
data Buffer to store read data.
dataSize Number of bytes to read.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Definition at line 176 of file AbstractIODevice.cc.
References lastError_, and readData().
readData()
virtual int64_t jiminy::AbstractIODevice::readData (void * data, int64_t dataSize) pure virtual
Read data in the device.
Parameters
data Buffer of data to read.
dataSize Number of bytes to read.
Returns
the number of bytes read, -1 in case of error
Implemented in jiminy::MemoryDevice, and jiminy::FileDevice.
Referenced by read().
seek()
hresult_t jiminy::AbstractIODevice::seek (int64_t pos) virtual
Move the current position cursor to pos if possible.
Parameters
pos Desired new position of the cursor.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Reimplemented in jiminy::MemoryDevice, and jiminy::FileDevice.
Definition at line 133 of file AbstractIODevice.cc.
References lastError_.
setBlockingMode()
hresult_t jiminy::AbstractIODevice::setBlockingMode (bool_t shouldBlock) virtual
Set the device blocking fashion.
Returns
The latest generated error.
Reimplemented in jiminy::MemoryDevice.
Definition at line 197 of file AbstractIODevice.cc.
References lastError_.
size()
int64_t jiminy::AbstractIODevice::size (void) virtual
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
Returns
The size of the device.
Reimplemented in jiminy::FileDevice, and jiminy::MemoryDevice.
Definition at line 121 of file AbstractIODevice.cc.
References bytesAvailable().
Referenced by jiminy::FileDevice::bytesAvailable().
supportedModes()
enum OpenMode jiminy::AbstractIODevice::supportedModes (void) const
Returns
The supported opening modes.
Definition at line 96 of file AbstractIODevice.cc.
write() [1/2]
template<typename T > hresult_t jiminy::AbstractIODevice::write (T const & valueIn)
Write data in the device.
The default implementation manage only POD type. For specific type, the template shall be extended with specific implementation.
Parameters
Value to write into the device.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Definition at line 18 of file AbstractIODevice.tpp.
Referenced by removeBackend(), jiminy::FileDevice::writeData(), and jiminy::TelemetryRecorder::writeDataBinary().
write() [2/2]
hresult_t jiminy::AbstractIODevice::write (void const * data, int64_t dataSize) virtual
Write data in the device.
Parameters
data Buffer of data to write.
dataSize Number of bytes to write.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Definition at line 155 of file AbstractIODevice.cc.
References lastError_, and writeData().
writeData()
virtual int64_t jiminy::AbstractIODevice::writeData (void const * data, int64_t dataSize) pure virtual
Write data in the device.
Parameters
data Buffer of data to write.
dataSize Number of bytes to write.
Returns
the number of bytes written, -1 in case of error
Implemented in jiminy::MemoryDevice, and jiminy::FileDevice.
Referenced by write().
The documentation for this class was generated from the following files:
core/include/jiminy/core/io/AbstractIODevice.h
core/include/jiminy/core/io/AbstractIODevice.tpp
core/src/io/AbstractIODevice.cc