jiminy: jiminy::AbstractMotorBase Class Reference
jiminy::AbstractMotorBase Class Reference abstract
Classes
struct abstractMotorOptions_t
Public Member Functions
virtual configHolder_t getDefaultMotorOptions (void)
Dictionary gathering the configuration options shared between motors.
AbstractMotorBase (AbstractMotorBase const &abstractMotor)=delete
Forbid the copy of the class.
AbstractMotorBase & operator= (AbstractMotorBase const &other)=delete
AbstractMotorBase (std::string const &name)
Constructor.
virtual hresult_t refreshProxies (void)
Refresh the proxies.
virtual void resetAll (void)
Reset the internal state of the motors.
configHolder_t getOptions (void) const
Get the configuration options of the motor.
float64_t const & get (void) const
Get the actual effort of the motor at the current time.
vectorN_t const & getAll (void) const
Get the actual effort of all the motors at the current time.
virtual hresult_t setOptions (configHolder_t const &motorOptions)
Set the configuration options of the motor.
hresult_t setOptionsAll (configHolder_t const &motorOptions)
Set the same configuration options for every motors.
bool_t const & getIsInitialized (void) const
Get isInitialized_.
std::string const & getName (void) const
Get name_.
int32_t const & getIdx (void) const
Get motorIdx_.
std::string const & getJointName (void) const
Get jointName_.
int32_t const & getJointModelIdx (void) const
Get jointModelIdx_.
joint_t const & getJointType (void) const
Get jointType_.
int32_t const & getJointPositionIdx (void) const
Get jointPositionIdx_.
int32_t const & getJointVelocityIdx (void) const
Get jointVelocityIdx_.
float64_t const & getEffortLimit (void) const
Get effortLimit_.
float64_t const & getRotorInertia (void) const
Get rotorInertia_.
virtual hresult_t computeEffort (float64_t const &t, float64_t const &q, float64_t const &v, float64_t const &a, float64_t const &uCommand)=0
Request the motor to update its actual effort based of the input data.
hresult_t computeEffortAll (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, Eigen::Ref< vectorN_t const > const &a, vectorN_t const &uCommand)
Request every motors to update their actual effort based of the input data.
Public Attributes
std::unique_ptr< abstractMotorOptions_t const > baseMotorOptions_
Structure with the parameters of the motor.
Protected Member Functions
float64_t & data (void)
Get a reference to the last data buffer corresponding to the actual effort of the motor.
Protected Attributes
configHolder_t motorOptionsHolder_
Dictionary with the parameters of the motor.
bool_t isInitialized_
Flag to determine whether the controller has been initialized or not.
bool_t isAttached_
Flag to determine whether the motor is attached to a robot.
Robot const * robot_
Robot for which the command and internal dynamics.
std::string name_
Name of the motor.
int32_t motorIdx_
Index of the motor in the measurement buffer.
std::string jointName_
int32_t jointModelIdx_
joint_t jointType_
int32_t jointPositionIdx_
int32_t jointVelocityIdx_
float64_t effortLimit_
float64_t rotorInertia_
Private Member Functions
hresult_t attach (Robot const *robot, MotorSharedDataHolder_t *sharedHolder)
Attach the sensor to a robot.
hresult_t detach (void)
Detach the sensor from the robot.
Private Attributes
friend Robot
MotorSharedDataHolder_t * sharedHolder_
Shared data between every motors associated with the robot.
Detailed Description
Definition at line 49 of file AbstractMotor.h.
Constructor & Destructor Documentation
AbstractMotorBase()
jiminy::AbstractMotorBase::AbstractMotorBase (std::string const & name)
Constructor.
Parameters
[in] robot Robot
[in] name Name of the motor
Definition at line 9 of file AbstractMotor.cc.
References detach(), getDefaultMotorOptions(), isAttached_, and setOptions().
Member Function Documentation
attach()
hresult_t jiminy::AbstractMotorBase::attach (Robot const * robot, MotorSharedDataHolder_t * sharedHolder) private
Attach the sensor to a robot.
This method must be called before initializing the sensor.
Definition at line 39 of file AbstractMotor.cc.
References isAttached_.
computeEffort()
virtual hresult_t jiminy::AbstractMotorBase::computeEffort (float64_t const & t, float64_t const & q, float64_t const & v, float64_t const & a, float64_t const & uCommand) pure virtual
Request the motor to update its actual effort based of the input data.
It assumes that the internal state of the robot is consistent with the input arguments.
Parameters
[in] t Current time
[in] q Current configuration of the motor
[in] v Current velocity of the motor
[in] a Current acceleration of the motor
[in] u Current command effort of the motor
Implemented in jiminy::SimpleMotor.
computeEffortAll()
hresult_t jiminy::AbstractMotorBase::computeEffortAll (float64_t const & t, Eigen::Ref< vectorN_t const > const & q, Eigen::Ref< vectorN_t const > const & v, Eigen::Ref< vectorN_t const > const & a, vectorN_t const & uCommand)
Request every motors to update their actual effort based of the input data.
It assumes that the internal state of the robot is consistent with the input arguments.
Remarks
This method is not intended to be called manually. The Robot to which the motor is added is taking care of it while updating the state of the motors.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[in] a Current acceleration vector
[in] u Current command effort vector
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 301 of file AbstractMotor.cc.
getEffortLimit()
float64_t const & jiminy::AbstractMotorBase::getEffortLimit (void) const
Get effortLimit_.
It is the maximum effort of the motor.
Definition at line 291 of file AbstractMotor.cc.
getIdx()
int32_t const & jiminy::AbstractMotorBase::getIdx (void) const
Get motorIdx_.
It is the index of the motor.
Definition at line 261 of file AbstractMotor.cc.
References motorIdx_.
getIsInitialized()
bool_t const & jiminy::AbstractMotorBase::getIsInitialized (void) const
Get isInitialized_.
It is a flag used to determine if the motor has been initialized.
Definition at line 251 of file AbstractMotor.cc.
References isInitialized_.
getJointModelIdx()
int32_t const & jiminy::AbstractMotorBase::getJointModelIdx (void) const
Get jointModelIdx_.
It is the index of the joint associated with the motor in the kinematic tree.
Definition at line 271 of file AbstractMotor.cc.
getJointName()
std::string const & jiminy::AbstractMotorBase::getJointName (void) const
Get jointName_.
It is the name of the joint associated with the motor.
Definition at line 266 of file AbstractMotor.cc.
getJointPositionIdx()
int32_t const & jiminy::AbstractMotorBase::getJointPositionIdx (void) const
Get jointPositionIdx_.
It is the index of the joint associated with the motor in the configuration vector.
Definition at line 281 of file AbstractMotor.cc.
getJointType()
joint_t const & jiminy::AbstractMotorBase::getJointType (void) const
Get jointType_.
It is the type of joint associated with the motor.
Definition at line 276 of file AbstractMotor.cc.
getJointVelocityIdx()
int32_t const & jiminy::AbstractMotorBase::getJointVelocityIdx (void) const
Get jointVelocityIdx_.
It is the index of the joint associated with the motor in the velocity vector.
Definition at line 286 of file AbstractMotor.cc.
getName()
std::string const & jiminy::AbstractMotorBase::getName (void) const
Get name_.
It is the name of the motor.
Definition at line 256 of file AbstractMotor.cc.
References name_.
getOptions()
configHolder_t jiminy::AbstractMotorBase::getOptions (void) const
Get the configuration options of the motor.
Returns
Dictionary with the parameters of the motor
Definition at line 148 of file AbstractMotor.cc.
References motorOptionsHolder_.
getRotorInertia()
float64_t const & jiminy::AbstractMotorBase::getRotorInertia (void) const
Get rotorInertia_.
It is the rotor inertia of the motor.
Definition at line 296 of file AbstractMotor.cc.
refreshProxies()
hresult_t jiminy::AbstractMotorBase::refreshProxies (void) virtual
Refresh the proxies.
Remarks
This method is not intended to be called manually. The Robot to which the motor is added is taking care of it when its own refresh method is called.
Definition at line 153 of file AbstractMotor.cc.
Referenced by resetAll(), and setOptions().
resetAll()
void jiminy::AbstractMotorBase::resetAll (void) virtual
Reset the internal state of the motors.
This method resets the internal state of the motor.
Remarks
This method is not intended to be called manually. The Robot to which the motor is added is taking care of it when its own reset method is called.
Definition at line 107 of file AbstractMotor.cc.
References jiminy::MotorSharedDataHolder_t::data_, jiminy::MotorSharedDataHolder_t::motors_, refreshProxies(), and sharedHolder_.
setOptions()
hresult_t jiminy::AbstractMotorBase::setOptions (configHolder_t const & motorOptions) virtual
Set the configuration options of the motor.
Parameters
[in] motorOptions Dictionary with the parameters of the motor
Reimplemented in jiminy::SimpleMotor.
Definition at line 120 of file AbstractMotor.cc.
References baseMotorOptions_, isAttached_, isInitialized_, motorOptionsHolder_, refreshProxies(), and robot_.
Referenced by AbstractMotorBase().
setOptionsAll()
hresult_t jiminy::AbstractMotorBase::setOptionsAll (configHolder_t const & motorOptions)
Set the same configuration options for every motors.
Parameters
[in] motorOptions Dictionary with the parameters used for any motor
Definition at line 236 of file AbstractMotor.cc.
The documentation for this class was generated from the following files:
core/include/jiminy/core/robot/AbstractMotor.h
core/src/robot/AbstractMotor.cc