jiminy: jiminy::ControllerFunctor< F1, F2 > Class Template Reference
jiminy::ControllerFunctor< F1, F2 > Class Template Reference
Public Member Functions
ControllerFunctor (ControllerFunctor const &controller)=delete
Forbid the copy of the class.
ControllerFunctor & operator= (ControllerFunctor const &controller)=delete
ControllerFunctor (F1 &commandFct, F2 &internalDynamicsFct)
Constructor.
ControllerFunctor (F1 &&commandFct, F2 &&internalDynamicsFct)
hresult_t computeCommand (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, vectorN_t &u) override
Compute the command.
hresult_t internalDynamics (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, vectorN_t &u) override
Emulate internal dynamics of the system at are not included in the physics engine.
Public Member Functions inherited from jiminy::AbstractController
virtual configHolder_t getDefaultControllerOptions ()
Dictionary gathering the configuration options shared between controllers.
AbstractController (AbstractController const &controller)=delete
AbstractController & operator= (AbstractController const &controller)=delete
virtual hresult_t initialize (Robot const *robot)
Set the parameters of the controller.
hresult_t registerVariable (std::vector< std::string > const &fieldnames, Eigen::Ref< vectorN_t > values)
Dynamically registered a Eigen Vector to the telemetry.
hresult_t registerVariable (std::string const &fieldName, float64_t const &value)
Dynamically registered a float64 to the telemetry.
template<typename T >
hresult_t registerConstant (std::string const &fieldName, T const &value)
Register a constant float64 to the telemetry.
void removeEntries (void)
Remove all variables dynamically registered to the telemetry.
configHolder_t getOptions (void) const
Get the configuration options of the controller.
void setOptions (configHolder_t const &ctrlOptions)
Set the configuration options of the controller.
virtual hresult_t configureTelemetry (std::shared_ptr< TelemetryData > telemetryData, std::string const &objectPrefixName="")
Configure the telemetry of the controller.
virtual void updateTelemetry (void)
Update the internal buffers of the telemetry associated with variables monitored by the controller.
virtual void reset (bool_t const &resetDynamicTelemetry=false)
Reset the internal state of the controller.
bool_t getIsInitialized (void) const
Get isInitialized_.
bool_t getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
Private Attributes
std::conditional_t< std::is_function< F1 >::value, std::add_pointer_t< F1 >, F1 > commandFct_
'Callable' computing the command
std::conditional_t< std::is_function< F2 >::value, std::add_pointer_t< F2 >, F2 > internalDynamicsFct_
'Callable' computing the internal dynamics
Additional Inherited Members
Public Attributes inherited from jiminy::AbstractController
std::unique_ptr< controllerOptions_t const > baseControllerOptions_
Structure with the parameters of the controller.
Protected Attributes inherited from jiminy::AbstractController
Robot const * robot_
Robot for which to compute the command and internal dynamics must be computed.
bool_t isInitialized_
Flag to determine whether the controller has been initialized or not.
bool_t isTelemetryConfigured_
Flag to determine whether the telemetry of the controller has been initialized or not.
configHolder_t ctrlOptionsHolder_
Dictionary with the parameters of the controller.
TelemetrySender telemetrySender_
Telemetry sender of the controller used to register and update telemetry variables.
sensorsDataMap_t sensorsData_
Detailed Description
template<typename F1, typename F2>
class jiminy::ControllerFunctor< F1, F2 >
Definition at line 29 of file ControllerFunctor.h.
Constructor & Destructor Documentation
ControllerFunctor()
template<typename F1 , typename F2 > jiminy::ControllerFunctor< F1, F2 >::ControllerFunctor (F1 & commandFct, F2 & internalDynamicsFct)
Constructor.
Remarks
A valid 'callable' is a function pointer, functor or lambda with signature: void(float64_t const & t, vectorN_t const & q, vectorN_t const & v, matrixN_t const & sensorsData[I]..., vectorN_t & u) where I is range(n), with n the number of different type of sensor.
Parameters
[in] commandFct 'Callable' computing the command
[in] internalDynamicsFct 'Callable' computing the internal dynamics
Definition at line 9 of file ControllerFunctor.tpp.
References jiminy::ControllerFunctor< F1, F2 >::commandFct_, jiminy::ControllerFunctor< F1, F2 >::ControllerFunctor(), and jiminy::ControllerFunctor< F1, F2 >::internalDynamicsFct_.
Member Function Documentation
computeCommand()
template<typename F1 , typename F2 > hresult_t jiminy::ControllerFunctor< F1, F2 >::computeCommand (float64_t const & t, Eigen::Ref< vectorN_t const > const & q, Eigen::Ref< vectorN_t const > const & v, vectorN_t & u) override virtual
Compute the command.
It assumes that the robot internal state (including sensors) is consistent with other input arguments. It fetches the sensor data automatically.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[out] u Output effort vector
Returns
Return code to determine whether the execution of the method was successful.
Implements jiminy::AbstractController.
Definition at line 29 of file ControllerFunctor.tpp.
References jiminy::AbstractController::getIsInitialized().
internalDynamics()
template<typename F1 , typename F2 > hresult_t jiminy::ControllerFunctor< F1, F2 >::internalDynamics (float64_t const & t, Eigen::Ref< vectorN_t const > const & q, Eigen::Ref< vectorN_t const > const & v, vectorN_t & u) override virtual
Emulate internal dynamics of the system at are not included in the physics engine.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[in] u Output effort vector
Returns
Return code to determine whether the execution of the method was successful.
Implements jiminy::AbstractController.
Definition at line 46 of file ControllerFunctor.tpp.
References jiminy::AbstractController::getIsInitialized().
The documentation for this class was generated from the following files:
core/include/jiminy/core/control/ControllerFunctor.h
core/include/jiminy/core/control/ControllerFunctor.tpp