jiminy: jiminy::AbstractController Class Reference
jiminy::AbstractController Class Reference abstract
Generic interface for any controller.
#include <AbstractController.h>
Classes
struct controllerOptions_t
Structure with the configuration options shared between controllers.
Public Member Functions
virtual configHolder_t getDefaultControllerOptions ()
Dictionary gathering the configuration options shared between controllers.
AbstractController (AbstractController const &controller)=delete
AbstractController & operator= (AbstractController const &controller)=delete
virtual hresult_t initialize (Robot const *robot)
Set the parameters of the controller.
hresult_t registerVariable (std::vector< std::string > const &fieldnames, Eigen::Ref< vectorN_t > values)
Dynamically registered a Eigen Vector to the telemetry.
hresult_t registerVariable (std::string const &fieldName, float64_t const &value)
Dynamically registered a float64 to the telemetry.
template<typename T >
hresult_t registerConstant (std::string const &fieldName, T const &value)
Register a constant float64 to the telemetry.
void removeEntries (void)
Remove all variables dynamically registered to the telemetry.
virtual hresult_t computeCommand (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, vectorN_t &u)=0
Compute the command.
virtual hresult_t internalDynamics (float64_t const &t, Eigen::Ref< vectorN_t const > const &q, Eigen::Ref< vectorN_t const > const &v, vectorN_t &u)=0
Emulate internal dynamics of the system at are not included in the physics engine.
configHolder_t getOptions (void) const
Get the configuration options of the controller.
void setOptions (configHolder_t const &ctrlOptions)
Set the configuration options of the controller.
virtual hresult_t configureTelemetry (std::shared_ptr< TelemetryData > telemetryData, std::string const &objectPrefixName="")
Configure the telemetry of the controller.
virtual void updateTelemetry (void)
Update the internal buffers of the telemetry associated with variables monitored by the controller.
virtual void reset (bool_t const &resetDynamicTelemetry=false)
Reset the internal state of the controller.
bool_t getIsInitialized (void) const
Get isInitialized_.
bool_t getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
Public Attributes
std::unique_ptr< controllerOptions_t const > baseControllerOptions_
Structure with the parameters of the controller.
Protected Attributes
Robot const * robot_
Robot for which to compute the command and internal dynamics must be computed.
bool_t isInitialized_
Flag to determine whether the controller has been initialized or not.
bool_t isTelemetryConfigured_
Flag to determine whether the telemetry of the controller has been initialized or not.
configHolder_t ctrlOptionsHolder_
Dictionary with the parameters of the controller.
TelemetrySender telemetrySender_
Telemetry sender of the controller used to register and update telemetry variables.
sensorsDataMap_t sensorsData_
Private Attributes
static_map_t< std::string, float64_t const * > registeredVariables_
Vector of dynamically registered telemetry variables.
static_map_t< std::string, std::string > registeredConstants_
Vector of dynamically registered telemetry constants.
Detailed Description
Generic interface for any controller.
Any controller must inherit from this base class and implement its virtual methods.
The controller used to initialize a Jiminy Engine is downcasted as an instance of AbstractController and polymorphism is used to call the actual implementations.
Definition at line 28 of file AbstractController.h.
Member Function Documentation
computeCommand()
virtual hresult_t jiminy::AbstractController::computeCommand (float64_t const & t, Eigen::Ref< vectorN_t const > const & q, Eigen::Ref< vectorN_t const > const & v, vectorN_t & u) pure virtual
Compute the command.
It assumes that the robot internal state (including sensors) is consistent with other input arguments. It fetches the sensor data automatically.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[out] u Output effort vector
Returns
Return code to determine whether the execution of the method was successful.
Implemented in jiminy::ControllerFunctor< F1, F2 >.
configureTelemetry()
hresult_t jiminy::AbstractController::configureTelemetry (std::shared_ptr< TelemetryData > telemetryData, std::string const & objectPrefixName = "") virtual
Configure the telemetry of the controller.
This method connects the controller-specific telemetry sender to a given telemetry data (which is unique for a given robot), so that it is later possible to register the variables that one want to monitor. Finally, the telemetry recoder logs every registered variables at each timestep in a memory buffer.
Remarks
This method is not intended to be called manually. The Engine is taking care of it before flushing the telemetry data at the end of each simulation steps.
Parameters
[in] telemetryData Shared pointer to the robot-wide telemetry data object
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 88 of file AbstractController.cc.
getIsInitialized()
bool_t jiminy::AbstractController::getIsInitialized (void) const
Get isInitialized_.
It is a flag used to determine if the controller has been initialized.
Remarks
Note that a controller can be considered initialized even if its telemetry is not properly configured. If not, it is the only to do before being ready to use.
Definition at line 228 of file AbstractController.cc.
References isInitialized_.
Referenced by jiminy::ControllerFunctor< F1, F2 >::computeCommand(), and jiminy::ControllerFunctor< F1, F2 >::internalDynamics().
getIsTelemetryConfigured()
bool_t jiminy::AbstractController::getIsTelemetryConfigured (void) const
Get isTelemetryConfigured_.
It is a flag used to determine if the telemetry of the controller has been initialized.
Definition at line 233 of file AbstractController.cc.
References isTelemetryConfigured_.
getOptions()
configHolder_t jiminy::AbstractController::getOptions (void) const
Get the configuration options of the controller.
Returns
Dictionary with the parameters of the controller
Definition at line 217 of file AbstractController.cc.
References ctrlOptionsHolder_.
initialize()
hresult_t jiminy::AbstractController::initialize (Robot const * robot) virtual
Set the parameters of the controller.
Parameters
[in] robot Robot
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 26 of file AbstractController.cc.
internalDynamics()
virtual hresult_t jiminy::AbstractController::internalDynamics (float64_t const & t, Eigen::Ref< vectorN_t const > const & q, Eigen::Ref< vectorN_t const > const & v, vectorN_t & u) pure virtual
Emulate internal dynamics of the system at are not included in the physics engine.
Parameters
[in] t Current time
[in] q Current configuration vector
[in] v Current velocity vector
[in] u Output effort vector
Returns
Return code to determine whether the execution of the method was successful.
Implemented in jiminy::ControllerFunctor< F1, F2 >.
registerConstant()
template<typename T > hresult_t jiminy::AbstractController::registerConstant (std::string const & fieldName, T const & value)
Register a constant float64 to the telemetry.
Register a constant to the telemetry.
Parameters
[in] fieldnames Name of the variable.
[in] values Variable to add to the telemetry
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 42 of file AbstractController.tpp.
References isTelemetryConfigured_.
registerVariable() [1/2]
hresult_t jiminy::AbstractController::registerVariable (std::vector< std::string > const & fieldnames, Eigen::Ref< vectorN_t > values)
Dynamically registered a Eigen Vector to the telemetry.
Internally, all it does is to store a reference to the variable, then it logs its value periodically. There is no update mechanism what so ever nor safety check. So the user has to take care of the life span of the variable, and to update it manually whenever it is necessary to do so.
Parameters
[in] fieldnames Name of each element of the variable. It will appear in the header of the log.
[in] values Eigen vector to add to the telemetry
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 140 of file AbstractController.cc.
References isTelemetryConfigured_.
registerVariable() [2/2]
hresult_t jiminy::AbstractController::registerVariable (std::string const & fieldName, float64_t const & value)
Dynamically registered a float64 to the telemetry.
Internally, all it does is to store a reference to the variable, then it logs its value periodically. There is no update mechanism what so ever nor safety check. So the user has to take care of the life span of the variable, and to update it manually whenever it is necessary to do so.
Parameters
[in] fieldnames Name of the variable. It will appear in the header of the log.
[in] values Variable to add to the telemetry
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 172 of file AbstractController.cc.
References isTelemetryConfigured_.
removeEntries()
void jiminy::AbstractController::removeEntries (void)
Remove all variables dynamically registered to the telemetry.
Note that one must reset Jiminy Engine for this to take effect.
Definition at line 200 of file AbstractController.cc.
References registeredConstants_, and registeredVariables_.
Referenced by reset().
reset()
void jiminy::AbstractController::reset (bool_t const & resetDynamicTelemetry = false) virtual
Reset the internal state of the controller.
Note that it resets the configuration of the telemetry.
Remarks
This method is not intended to be called manually. The Engine is taking care of it when its own reset method is called.
Parameters
[in] resetDynamicTelemetry Whether or not variables dynamically registered to the telemetry must be removed. Optional: False by default
Definition at line 72 of file AbstractController.cc.
References isTelemetryConfigured_, removeEntries(), and robot_.
setOptions()
void jiminy::AbstractController::setOptions (configHolder_t const & ctrlOptions)
Set the configuration options of the controller.
Note that one must reset Jiminy Engine for this to take effect.
Parameters
[in] ctrlOptions Dictionary with the parameters of the controller
Returns
Return code to determine whether the execution of the method was successful.
Definition at line 222 of file AbstractController.cc.
References baseControllerOptions_, and ctrlOptionsHolder_.
updateTelemetry()
void jiminy::AbstractController::updateTelemetry (void) virtual
Update the internal buffers of the telemetry associated with variables monitored by the controller.
As the main entry point for a user to log extra variables, the engine also passes the current state of the robot to enable logging of custom state-related variables.
Parameters
[in] t Current time.
[in] q Current position.
[in] v Current velocity.
Remarks
This method is not intended to be called manually. The Engine is taking care of it before flushing the telemetry data at the end of each simulation steps.
Definition at line 206 of file AbstractController.cc.
References isTelemetryConfigured_, registeredVariables_, telemetrySender_, and jiminy::TelemetrySender::updateValue().
The documentation for this class was generated from the following files:
core/include/jiminy/core/control/AbstractController.h
core/include/jiminy/core/control/AbstractController.tpp
core/src/control/AbstractController.cc