jiminy: jiminy::MemoryDevice Class Reference
jiminy::MemoryDevice Class Reference
Manage a memory buffer with IODevice interface.
#include <MemoryDevice.h>
Public Member Functions
MemoryDevice (int64_t size)
MemoryDevice (MemoryDevice const &other)
MemoryDevice (MemoryDevice &&other)
MemoryDevice (std::vector< uint8_t > &&initBuffer)
MemoryDevice & operator= (MemoryDevice const &other)
MemoryDevice & operator= (MemoryDevice &&other)
int64_t size (void) override
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
bool_t isSequential (void) const override
int64_t pos (void) override
int64_t bytesAvailable (void) override
Returns the number of bytes that are available for reading. Commonly used with sequential device.
hresult_t seek (int64_t pos) override
Move the current position cursor to pos if possible.
int64_t readData (void *data, int64_t dataSize) override
Read data in the device.
int64_t writeData (void const *data, int64_t dataSize) override
Write data in the device.
hresult_t setBlockingMode (bool_t) override
Set the device blocking fashion.
hresult_t resize (int64_t size) override
resize the device to provided size.
Public Member Functions inherited from jiminy::AbstractIODevice
hresult_t open (enum OpenMode mode)
Open the device.
hresult_t close (void)
Write data in the device.
enum OpenMode openModes (void) const
enum OpenMode supportedModes (void) const
bool_t isWritable (void) const
bool_t isReadable (void) const
bool_t isOpen (void) const
template<typename T >
hresult_t write (T const &valueIn)
Write data in the device.
virtual hresult_t write (void const *data, int64_t dataSize)
Write data in the device.
template<typename T >
hresult_t read (T &valueIn)
Read data in the device.
virtual hresult_t read (void *data, int64_t dataSize)
Read data from the device.
hresult_t getLastError (void) const
Retrieve the latest error. Usefull for call that do not return an error code directly.
bool_t isBackendValid ()
Set the device backend (reset the old one if any).
virtual void setBackend (std::unique_ptr< AbstractIODevice > io)
Set the device backend (reset the old one if any).
virtual void removeBackend (void)
Reset the device backend.
template<>
hresult_t read (std::vector< uint8_t > &v)
template<>
hresult_t read (std::vector< char_t > &v)
template<>
hresult_t write (std::string const &str)
template<>
hresult_t write (std::vector< uint8_t > const &v)
template<>
hresult_t write (std::vector< char_t > const &v)
template<>
hresult_t write (std::vector< uint64_t > const &v)
Protected Member Functions
hresult_t doOpen (enum OpenMode modes) override
hresult_t doClose (void) override
Private Attributes
std::vector< uint8_t > buffer_
int64_t currentPos_
Additional Inherited Members
Protected Attributes inherited from jiminy::AbstractIODevice
hresult_t lastError_ {hresult_t::SUCCESS}
Latest generated error.
std::unique_ptr< AbstractIODevice > io_ {nullptr}
Backend to use if any.
Detailed Description
Manage a memory buffer with IODevice interface.
Definition at line 12 of file MemoryDevice.h.
Member Function Documentation
bytesAvailable()
int64_t jiminy::MemoryDevice::bytesAvailable (void) inline override virtual
Returns the number of bytes that are available for reading. Commonly used with sequential device.
Returns
The available bytesfor reading.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 41 of file MemoryDevice.h.
References pos(), readData(), resize(), seek(), setBlockingMode(), and writeData().
isSequential()
bool_t jiminy::MemoryDevice::isSequential (void) const inline override virtual
Returns
true if the device is sequential (i.e socket), false if the device support random-access (i.e regular file).
Reimplemented from jiminy::AbstractIODevice.
Definition at line 31 of file MemoryDevice.h.
pos()
int64_t jiminy::MemoryDevice::pos (void) inline override virtual
Returns
The current cursor position (0 if there is not concept of position cursor).
Reimplemented from jiminy::AbstractIODevice.
Definition at line 36 of file MemoryDevice.h.
Referenced by bytesAvailable().
readData()
int64_t jiminy::MemoryDevice::readData (void * data, int64_t dataSize) override virtual
Read data in the device.
Parameters
data Buffer of data to read.
dataSize Number of bytes to read.
Returns
the number of bytes read, -1 in case of error
Implements jiminy::AbstractIODevice.
Definition at line 78 of file MemoryDevice.cc.
Referenced by bytesAvailable().
seek()
hresult_t jiminy::MemoryDevice::seek (int64_t pos) override virtual
Move the current position cursor to pos if possible.
Parameters
pos Desired new position of the cursor.
Returns
hresult_t::SUCCESS if successful, another hresult_t value otherwise.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 65 of file MemoryDevice.cc.
Referenced by bytesAvailable().
setBlockingMode()
hresult_t jiminy::MemoryDevice::setBlockingMode (bool_t shouldBlock) override virtual
Set the device blocking fashion.
Returns
The latest generated error.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 109 of file MemoryDevice.cc.
Referenced by bytesAvailable().
size()
int64_t jiminy::MemoryDevice::size (void) inline override virtual
For random-access devices, this function returns the size of the device. For sequential devices, bytesAvailable() is returned.
Returns
The size of the device.
Reimplemented from jiminy::AbstractIODevice.
Definition at line 26 of file MemoryDevice.h.
writeData()
int64_t jiminy::MemoryDevice::writeData (void const * data, int64_t dataSize) override virtual
Write data in the device.
Parameters
data Buffer of data to write.
dataSize Number of bytes to write.
Returns
the number of bytes written, -1 in case of error
Implements jiminy::AbstractIODevice.
Definition at line 93 of file MemoryDevice.cc.
Referenced by bytesAvailable().
The documentation for this class was generated from the following files:
core/include/jiminy/core/io/MemoryDevice.h
core/src/io/MemoryDevice.cc