var namespacejiminy =
[
    [ "pinocchio_overload", null, [
      [ "AbaBackwardStep", "structjiminy_1_1pinocchio__overload_1_1_aba_backward_step.html", "structjiminy_1_1pinocchio__overload_1_1_aba_backward_step" ]
    ] ],
    [ "stepper", null, [
      [ "runge_kutta", null, [
        [ "StepAdjusterImpl", "classjiminy_1_1stepper_1_1runge__kutta_1_1_step_adjuster_impl.html", "classjiminy_1_1stepper_1_1runge__kutta_1_1_step_adjuster_impl" ]
      ] ],
      [ "EulerExplicit", "classjiminy_1_1stepper_1_1_euler_explicit.html", "classjiminy_1_1stepper_1_1_euler_explicit" ]
    ] ],
    [ "AbstractConstraint", "classjiminy_1_1_abstract_constraint.html", "classjiminy_1_1_abstract_constraint" ],
    [ "AbstractController", "classjiminy_1_1_abstract_controller.html", "classjiminy_1_1_abstract_controller" ],
    [ "AbstractIODevice", "classjiminy_1_1_abstract_i_o_device.html", "classjiminy_1_1_abstract_i_o_device" ],
    [ "AbstractMotorBase", "classjiminy_1_1_abstract_motor_base.html", "classjiminy_1_1_abstract_motor_base" ],
    [ "AbstractSensorBase", "classjiminy_1_1_abstract_sensor_base.html", "classjiminy_1_1_abstract_sensor_base" ],
    [ "AbstractSensorTpl", "classjiminy_1_1_abstract_sensor_tpl.html", "classjiminy_1_1_abstract_sensor_tpl" ],
    [ "AppendBoostVariantToJson", "classjiminy_1_1_append_boost_variant_to_json.html", "classjiminy_1_1_append_boost_variant_to_json" ],
    [ "ControllerFunctor", "classjiminy_1_1_controller_functor.html", "classjiminy_1_1_controller_functor" ],
    [ "EffortSensor", "classjiminy_1_1_effort_sensor.html", "classjiminy_1_1_effort_sensor" ],
    [ "EncoderSensor", "classjiminy_1_1_encoder_sensor.html", "classjiminy_1_1_encoder_sensor" ],
    [ "Engine", "classjiminy_1_1_engine.html", "classjiminy_1_1_engine" ],
    [ "EngineMultiRobot", "classjiminy_1_1_engine_multi_robot.html", "classjiminy_1_1_engine_multi_robot" ],
    [ "FileDevice", "classjiminy_1_1_file_device.html", "classjiminy_1_1_file_device" ],
    [ "FixedFrameConstraint", "classjiminy_1_1_fixed_frame_constraint.html", "classjiminy_1_1_fixed_frame_constraint" ],
    [ "flexibleJointData_t", "structjiminy_1_1flexible_joint_data__t.html", "structjiminy_1_1flexible_joint_data__t" ],
    [ "forceCoupling_t", "structjiminy_1_1force_coupling__t.html", "structjiminy_1_1force_coupling__t" ],
    [ "forceImpulse_t", "structjiminy_1_1force_impulse__t.html", "structjiminy_1_1force_impulse__t" ],
    [ "forceProfile_t", "structjiminy_1_1force_profile__t.html", "structjiminy_1_1force_profile__t" ],
    [ "ForceSensor", "classjiminy_1_1_force_sensor.html", "classjiminy_1_1_force_sensor" ],
    [ "ImuSensor", "classjiminy_1_1_imu_sensor.html", "classjiminy_1_1_imu_sensor" ],
    [ "IndexByIdx", "structjiminy_1_1_index_by_idx.html", null ],
    [ "IndexByName", "structjiminy_1_1_index_by_name.html", null ],
    [ "is_eigen", "structjiminy_1_1is__eigen.html", null ],
    [ "is_eigen< T, typename std::enable_if< isEigenObject< T >::value >::type >", "structjiminy_1_1is__eigen_3_01_t_00_01typename_01std_1_1enable__if_3_01is_eigen_object_3_01_t_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "is_eigen_vector", "structjiminy_1_1is__eigen__vector.html", null ],
    [ "is_eigen_vector< T, typename std::enable_if< isEigenVector< T >::value >::type >", "structjiminy_1_1is__eigen__vector_3_01_t_00_01typename_01std_1_1enable__if_3_01is_eigen_vector_31f15da7a28ec1e767f4b1a5f780df70e.html", null ],
    [ "is_map", "structjiminy_1_1is__map.html", null ],
    [ "is_map< T, typename std::enable_if< isMap< T >::value >::type >", "structjiminy_1_1is__map_3_01_t_00_01typename_01std_1_1enable__if_3_01is_map_3_01_t_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "is_vector", "structjiminy_1_1is__vector.html", null ],
    [ "is_vector< std::vector< T > >", "structjiminy_1_1is__vector_3_01std_1_1vector_3_01_t_01_4_01_4.html", null ],
    [ "isEigenObject", "structjiminy_1_1is_eigen_object.html", null ],
    [ "isEigenVector", "structjiminy_1_1is_eigen_vector.html", null ],
    [ "isMap", "structjiminy_1_1is_map.html", null ],
    [ "JsonLoader", "classjiminy_1_1_json_loader.html", "classjiminy_1_1_json_loader" ],
    [ "JsonWriter", "classjiminy_1_1_json_writer.html", "classjiminy_1_1_json_writer" ],
    [ "memHeader", "structjiminy_1_1mem_header.html", "structjiminy_1_1mem_header" ],
    [ "MemoryBuffer", "classjiminy_1_1_memory_buffer.html", "classjiminy_1_1_memory_buffer" ],
    [ "MemoryDevice", "classjiminy_1_1_memory_device.html", "classjiminy_1_1_memory_device" ],
    [ "Model", "classjiminy_1_1_model.html", "classjiminy_1_1_model" ],
    [ "MotorSharedDataHolder_t", "structjiminy_1_1_motor_shared_data_holder__t.html", "structjiminy_1_1_motor_shared_data_holder__t" ],
    [ "MutexLocal", "classjiminy_1_1_mutex_local.html", "classjiminy_1_1_mutex_local" ],
    [ "Robot", "classjiminy_1_1_robot.html", "classjiminy_1_1_robot" ],
    [ "sensorDataTypePair_t", "structjiminy_1_1sensor_data_type_pair__t.html", "structjiminy_1_1sensor_data_type_pair__t" ],
    [ "SensorSharedDataHolder_t", "structjiminy_1_1_sensor_shared_data_holder__t.html", "structjiminy_1_1_sensor_shared_data_holder__t" ],
    [ "SimpleMotor", "classjiminy_1_1_simple_motor.html", "classjiminy_1_1_simple_motor" ],
    [ "stepperState_t", "structjiminy_1_1stepper_state__t.html", "structjiminy_1_1stepper_state__t" ],
    [ "systemDataHolder_t", "structjiminy_1_1system_data_holder__t.html", "structjiminy_1_1system_data_holder__t" ],
    [ "systemState_t", "structjiminy_1_1system_state__t.html", "structjiminy_1_1system_state__t" ],
    [ "TelemetryData", "classjiminy_1_1_telemetry_data.html", "classjiminy_1_1_telemetry_data" ],
    [ "TelemetryRecorder", "classjiminy_1_1_telemetry_recorder.html", "classjiminy_1_1_telemetry_recorder" ],
    [ "TelemetrySender", "classjiminy_1_1_telemetry_sender.html", "classjiminy_1_1_telemetry_sender" ],
    [ "Timer", "classjiminy_1_1_timer.html", "classjiminy_1_1_timer" ],
    [ "type_identity", "structjiminy_1_1type__identity.html", "structjiminy_1_1type__identity" ]
];