#!/usr/bin/env python

import json
import argparse
import numpy as np
import os

from exo_simu_py import visualize


csv_log_path = '/home/builder/wdc_workspace/log.csv'
fast_mode = False
visualize(csv_log_path, fast_mode)