#!/usr/bin/env python

import json
import argparse
import numpy as np
import os

from exo_simu_py import load_csv_log, visualize


csv_log_path = os.path.dirname(os.path.realpath(__file__)) + '/log.csv'
fast_mode = False
visualize(load_csv_log(csv_log_path), fast_mode)